### ISSUE TITLE
GPU 관련으로 문의드립니다.

### ISSUE THREAD

**Issue by ryanh9801** [nawnoes/dialogLM#17]
안녕하세요?
지금 run_auto_regressive.py를 실행해보고 있고 돌아가기는 하는데
제가 잘못한 것인지 모르겠지만 CUDA GPU를 전혀 사용하지 못하고 있습니다.

torch.cuda.is_available() 을 확인하여보면 분명히 TRUE로 나오는데 그냥 CPU로 학습을 시작하여 1epoch 마다 48시간씩 걸린다고 계속 나옵니다.

어떻게 해결해야할까요?

**Comment by nawnoes** [comment]
안녕하세요
`run_auto_regressive.py` 파일 확인해보니 현재 올려져 있는 코드로는
GPU로 돌아가지 않게 되어있습니다.

`train-kogpt2-for-wellness.ipynb` 참고하셔서 gpu에서 돌아가도록
입력과 모델의 device 설정 하는 부분을 수정하면 gpu에서 학습하실 수  있을거 같습니다

**Comment by ryanh9801** [comment]
해결되었습니다.
감사합니다.
